plugins:
  - coffee
extends:
  - plugin:coffee/all
  - plugin:coffee/prettier-run-as-rule
rules:
  coffee/prefer-destructuring: [error, {object: true}]
  no-undef: error
  coffee/id-length: off
  max-lines: off
  coffee/no-magic-numbers: off
  coffee/capitalized-comments: off
  max-statements: off
  coffee/max-lines-per-function: off
  coffee/vars-on-top: off
  coffee/no-constant-condition: off
  coffee/no-return-assign: off
  coffee/no-use-before-define: off
  sort-keys: off
  coffee/no-underscore-dangle: off
  no-multi-assign: off
  new-cap: off
  coffee/spread-direction: off
  no-inline-comments: off
  line-comment-position: off
  require-unicode-regexp: off
  no-warning-comments: off
  global-require: off
  no-sync: off
  coffee/multiline-comment-style: off
  coffee/spaced-comment: off
  coffee/guard-for-in: off
  no-continue: off
  no-plusplus: off
  coffee/complexity: off
  coffee/no-implicit-coercion: off
  coffee/no-nested-interpolation: off
  coffee/no-cond-assign: off
  no-process-exit: off
  no-bitwise: off
env:
  node: true
  jest: true
